INSERT INTO golpes (golpe) VALUES
('Tai Otoshi'),
('Ippon Seoi Nage'),
('Morote Seoi Nage'),
('Kata Guruma'),
('Sumi Otoshi'),
('Sukui Nage'),
('Obi Otoshi'),
('Uki Otoshi'),
('Yama Arashi'),
('O Goshi'),
('Uki Goshi'),
('Harai Goshi'),
('Tsuri Goshi'),
('Koshi Guruma'),
('Tsuri Komi Goshi'),
('Ushiro Goshi'),
('Hane Goshi'),
('O Soto Gari'),
('O Uchi Gari'),
('Ko Soto Gari'),
('Ko Uchi Gari'),
('De Ashi Harai'),
('Harai Tsurikomi Ashi'),
('Okuri Ashi Harai'),
('Sasae Tsurikomi Ashi'),
('Uchi Mata'),
('Tomoe Nage'),
('Ura Nage'),
('Sumi Gaeshi'),
('Hikikomi Gaeshi'),
('Tawara Gaeshi'),
('Yoko Otoshi'),
('Yoko Gake'),
('Yoko Guruma'),
('Uki Waza'),
('Yoko Wakare'),
('Tani Otoshi');